// Candidate language packs for the single currently reachable Task-11 form.
// The source English form remains the canonical reference; each localized form
// carries its own answer key so performance is never scored against English.
export const SPEECH_IN_NOISE_LANGUAGE_OVERRIDES = Object.freeze({
  nl: {
    speech_a: {
      passage: 'Een kustplaats overstroomde tientallen jaren lang iedere winter. In plaats van één hogere muur te bouwen, herstelden de bewoners de duinen, maakten zij een moeras breder en verhoogden zij de laagste voetpaden. De eerste storm na het project bracht nog steeds hoog water, maar het moeras remde de stormvloed en de duinen beschermden woningen tegen de golven. Ingenieurs waarschuwden dat geen enkele maatregel alle risico kon wegnemen. De gemeente combineerde het landschapswerk daarom met duidelijke evacuatieroutes en regelmatige waarschuwingsoefeningen. Het project slaagde doordat natuurlijke barrières, praktische planning en voorbereiding van de gemeenschap elkaar ondersteunden. Het schiep ook nieuw leefgebied en maakte de kust bij rustig weer beter toegankelijk. Voor de bouw brachten landmeters in kaart waar water de straten binnenkwam en waar oudere bewoners hulp nodig zouden hebben om hun woning te verlaten. Vrijwilligers oefenden de nieuwe routes bij droog weer; daarbij bleek één brug te smal voor hulpvoertuigen. Het plan werd vóór het volgende stormseizoen aangepast. Lokale bedrijven beloofden tijdelijke barrières op te slaan en scholen voegden overstromingsinstructies toe aan hun veiligheidsoefeningen. Metingen na elke storm werden vergeleken met eerdere gegevens, zodat duinen en moeras konden worden hersteld waar erosie het grootst was. Sommige bewoners wilden aanvankelijk één zichtbare verdediging omdat die eenvoudiger leek. Openbare workshops lieten zien waarom meerdere verbonden maatregelen meer veerkracht boden: als één onderdeel beschadigd raakte, konden de andere nog steeds schade beperken. De gemeente publiceerde onderhoudskosten en inspectieresultaten in plaats van de opening als einde van het project te zien. Deze voortdurende beoordeling hielp de plaats zich aan te passen aan veranderende zeespiegels en weersomstandigheden. De aanpak beloofde geen volmaakte veiligheid. Zij combineerde natuurlijke bescherming, betrouwbare infrastructuur, waarschuwingen, evacuatie-oefening en gedeelde verantwoordelijkheid zodat het resterende risico openlijk kon worden beheerd.',
      mainIdea: 'Gelaagde natuurlijke en praktische maatregelen verminderden het overstromingsrisico.',
      mainIdeaOptions: ['Gelaagde natuurlijke en praktische maatregelen verminderden het overstromingsrisico.', 'De plaats stopte alle stormen door één muur te bouwen.', 'Toerisme was de enige reden om de kust te herstellen.'],
      keyDetailQuestion: 'Wat remde de stormvloed?',
      keyDetail: 'het moeras',
    },
  },
  de: {
    speech_a: {
      passage: 'Eine Küstenstadt wurde jahrzehntelang jeden Winter überflutet. Statt eine einzige höhere Mauer zu bauen, stellten die Bewohner Dünen wieder her, verbreiterten ein Marschgebiet und erhöhten die niedrigsten Fußwege. Der erste Sturm nach dem Projekt brachte weiterhin hohes Wasser, doch das Marschgebiet verlangsamte die Sturmflut und die Dünen schützten Häuser vor den Wellen. Ingenieure warnten, dass keine einzelne Maßnahme jedes Risiko beseitigen könne. Deshalb verband der Stadtrat die Landschaftsarbeiten mit klaren Evakuierungswegen und regelmäßigen Warnübungen. Das Projekt gelang, weil natürliche Barrieren, praktische Planung und die Vorbereitung der Gemeinschaft einander unterstützten. Es schuf außerdem neuen Lebensraum und machte die Küste bei ruhigem Wetter leichter zugänglich. Vor Baubeginn kartierten Vermesser, wo Wasser in Straßen eindrang und wo ältere Bewohner Hilfe beim Verlassen ihrer Häuser benötigen würden. Freiwillige übten die neuen Wege bei trockenem Wetter; dabei zeigte sich, dass eine Brücke für Einsatzfahrzeuge zu schmal war. Der Plan wurde vor der nächsten Sturmsaison angepasst. Örtliche Unternehmen erklärten sich bereit, provisorische Barrieren zu lagern, und Schulen nahmen Hochwasserhinweise in ihre Sicherheitsübungen auf. Messungen nach jedem Sturm wurden mit früheren Daten verglichen, damit Dünen und Marschgebiet dort repariert werden konnten, wo die Erosion am stärksten war. Einige Bewohner wollten zunächst einen einzigen sichtbaren Schutz, weil er einfacher erschien. Öffentliche Workshops zeigten, warum mehrere verbundene Maßnahmen widerstandsfähiger waren: Wenn ein Element beschädigt wurde, konnten die anderen weiterhin Schäden mindern. Der Stadtrat veröffentlichte Wartungskosten und Prüfergebnisse, statt die Eröffnung als Ende des Projekts zu betrachten. Diese fortlaufende Überprüfung half der Stadt, sich an veränderte Meeresspiegel und Wetterbedingungen anzupassen. Der Ansatz versprach keine perfekte Sicherheit. Er verband natürlichen Schutz, verlässliche Infrastruktur, Warnungen, Evakuierungsübungen und gemeinsame Verantwortung, damit das verbleibende Risiko offen bewältigt werden konnte.',
      mainIdea: 'Mehrere natürliche und praktische Maßnahmen verringerten das Hochwasserrisiko.',
      mainIdeaOptions: ['Mehrere natürliche und praktische Maßnahmen verringerten das Hochwasserrisiko.', 'Die Stadt stoppte alle Stürme durch eine einzige Mauer.', 'Tourismus war der einzige Grund für die Wiederherstellung der Küste.'],
      keyDetailQuestion: 'Was verlangsamte die Sturmflut?',
      keyDetail: 'das Marschgebiet',
    },
  },
  fr: {
    speech_a: {
      passage: 'Une ville côtière était inondée chaque hiver depuis des décennies. Au lieu de construire un seul mur plus haut, les habitants ont restauré les dunes, élargi un marais et surélevé les chemins les plus bas. La première tempête après le projet a encore apporté beaucoup d’eau, mais le marais a ralenti la surcote et les dunes ont protégé les habitations des vagues. Des ingénieurs ont averti qu’aucune mesure unique ne pouvait supprimer tout risque. Le conseil municipal a donc associé ces travaux paysagers à des itinéraires d’évacuation clairs et à des exercices d’alerte réguliers. Le projet a réussi parce que les barrières naturelles, une planification pratique et la préparation de la communauté se sont renforcées mutuellement. Il a aussi créé de nouveaux habitats et rendu le littoral plus facile à visiter par temps calme. Avant les travaux, des géomètres ont repéré les endroits où l’eau entrait dans les rues et ceux où les habitants âgés auraient besoin d’aide pour quitter leur logement. Des bénévoles ont répété les nouveaux itinéraires par temps sec, ce qui a révélé qu’un pont était trop étroit pour les véhicules d’urgence. Le plan a été modifié avant la saison suivante. Des entreprises locales ont accepté de stocker des barrières temporaires et les écoles ont ajouté des consignes d’inondation à leurs exercices de sécurité. Les mesures prises après chaque tempête ont été comparées aux données antérieures afin de réparer dunes et marais là où l’érosion était la plus forte. Certains habitants souhaitaient d’abord une seule défense visible parce qu’elle semblait plus simple. Des ateliers publics ont montré pourquoi plusieurs mesures liées offraient davantage de résilience : si un élément était endommagé, les autres pouvaient encore réduire les dégâts. Le conseil a publié les coûts d’entretien et les résultats des inspections au lieu de considérer l’inauguration comme la fin du projet. Cette révision continue a aidé la ville à s’adapter à l’évolution du niveau de la mer et du climat. L’approche ne promettait pas une sécurité parfaite. Elle associait protection naturelle, infrastructures fiables, alertes, exercices d’évacuation et responsabilité partagée afin de gérer ouvertement le risque restant.',
      mainIdea: 'Des mesures naturelles et pratiques combinées ont réduit le risque d’inondation.',
      mainIdeaOptions: ['Des mesures naturelles et pratiques combinées ont réduit le risque d’inondation.', 'La ville a arrêté toutes les tempêtes en construisant un seul mur.', 'Le tourisme était la seule raison de restaurer le littoral.'],
      keyDetailQuestion: 'Qu’est-ce qui a ralenti la surcote ?',
      keyDetail: 'le marais',
    },
  },
  es: {
    speech_a: {
      passage: 'Un pueblo costero se inundaba cada invierno desde hacía décadas. En lugar de construir un único muro más alto, los residentes restauraron las dunas, ampliaron una marisma y elevaron los senderos más bajos. La primera tormenta tras el proyecto siguió trayendo mucha agua, pero la marisma frenó la marejada y las dunas protegieron las viviendas de las olas. Los ingenieros advirtieron que ninguna medida aislada podía eliminar todo el riesgo. Por ello, el ayuntamiento combinó las obras paisajísticas con rutas claras de evacuación y pruebas periódicas de alerta. El proyecto tuvo éxito porque las barreras naturales, la planificación práctica y la preparación de la comunidad se apoyaron mutuamente. También creó nuevo hábitat y facilitó visitar la costa cuando el tiempo estaba tranquilo. Antes de empezar la obra, los topógrafos cartografiaron dónde entraba el agua en las calles y dónde los residentes mayores necesitarían ayuda para salir de sus casas. Los voluntarios practicaron las nuevas rutas en tiempo seco y descubrieron que un puente era demasiado estrecho para los vehículos de emergencia. El plan se ajustó antes de la siguiente temporada de tormentas. Los comercios locales aceptaron guardar barreras temporales y las escuelas añadieron instrucciones sobre inundaciones a sus ejercicios de seguridad. Las mediciones después de cada tormenta se compararon con registros anteriores para reparar las dunas y la marisma donde la erosión fuera mayor. Algunos residentes querían inicialmente una sola defensa visible porque parecía más sencilla. Los talleres públicos mostraron por qué varias medidas conectadas ofrecían mayor resiliencia: si un elemento resultaba dañado, los demás aún podían reducir el perjuicio. El ayuntamiento publicó los costes de mantenimiento y los resultados de las inspecciones en vez de tratar la inauguración como el final del proyecto. Esta revisión continua ayudó al pueblo a adaptarse a los cambios del nivel del mar y del clima. El enfoque no prometía seguridad perfecta. Combinaba protección natural, infraestructura fiable, alertas, prácticas de evacuación y responsabilidad compartida para gestionar abiertamente el riesgo restante.',
      mainIdea: 'Las medidas naturales y prácticas combinadas redujeron el riesgo de inundación.',
      mainIdeaOptions: ['Las medidas naturales y prácticas combinadas redujeron el riesgo de inundación.', 'El pueblo detuvo todas las tormentas construyendo un solo muro.', 'El turismo era la única razón para restaurar la costa.'],
      keyDetailQuestion: '¿Qué frenó la marejada?',
      keyDetail: 'la marisma',
    },
  },
  it: {
    speech_a: {
      passage: 'Una città costiera si allagava ogni inverno da decenni. Invece di costruire un unico muro più alto, gli abitanti ripristinarono le dune, ampliarono una palude costiera e rialzarono i sentieri più bassi. La prima tempesta dopo il progetto portò ancora acqua alta, ma la palude rallentò la mareggiata e le dune protessero le case dalle onde. Gli ingegneri avvertirono che nessuna singola misura poteva eliminare ogni rischio. Il consiglio comunale unì quindi i lavori sul paesaggio a chiare vie di evacuazione e a prove di allarme regolari. Il progetto riuscì perché barriere naturali, pianificazione pratica e preparazione della comunità si sostennero a vicenda. Creò inoltre nuovi habitat e rese la costa più facile da visitare con il bel tempo. Prima dei lavori, i tecnici mapparono i punti in cui l’acqua entrava nelle strade e quelli in cui gli abitanti anziani avrebbero avuto bisogno di aiuto per uscire di casa. I volontari provarono i nuovi percorsi con tempo asciutto e scoprirono che un ponte era troppo stretto per i mezzi di emergenza. Il piano fu corretto prima della stagione successiva. Le imprese locali accettarono di conservare barriere temporanee e le scuole aggiunsero istruzioni sulle alluvioni alle esercitazioni di sicurezza. Le misurazioni dopo ogni tempesta furono confrontate con i dati precedenti, così dune e palude potevano essere riparate dove l’erosione era maggiore. Alcuni abitanti desideravano inizialmente un’unica difesa visibile perché sembrava più semplice. I laboratori pubblici mostrarono perché più misure collegate offrivano maggiore resilienza: se un elemento veniva danneggiato, gli altri potevano ancora ridurre il danno. Il consiglio pubblicò costi di manutenzione e risultati delle ispezioni invece di considerare l’inaugurazione la fine del progetto. Questa revisione continua aiutò la città ad adattarsi ai cambiamenti del livello del mare e del clima. L’approccio non prometteva sicurezza perfetta. Combinava protezione naturale, infrastrutture affidabili, avvisi, esercitazioni di evacuazione e responsabilità condivisa per gestire apertamente il rischio residuo.',
      mainIdea: 'Misure naturali e pratiche combinate hanno ridotto il rischio di alluvione.',
      mainIdeaOptions: ['Misure naturali e pratiche combinate hanno ridotto il rischio di alluvione.', 'La città ha fermato tutte le tempeste costruendo un solo muro.', 'Il turismo era l’unica ragione per ripristinare la costa.'],
      keyDetailQuestion: 'Che cosa ha rallentato la mareggiata?',
      keyDetail: 'la palude',
    },
  },
  pt: {
    speech_a: {
      passage: 'Uma vila costeira sofria inundações todos os invernos havia décadas. Em vez de construir um único muro mais alto, os moradores restauraram as dunas, alargaram uma zona pantanosa e elevaram os caminhos mais baixos. A primeira tempestade depois do projeto ainda trouxe muita água, mas a zona pantanosa abrandou a maré de tempestade e as dunas protegeram as casas das ondas. Os engenheiros alertaram que nenhuma medida isolada poderia eliminar todo o risco. Por isso, a câmara municipal combinou o trabalho na paisagem com rotas de evacuação claras e testes de aviso regulares. O projeto resultou porque barreiras naturais, planeamento prático e preparação da comunidade se apoiaram mutuamente. Também criou novo habitat e tornou a costa mais fácil de visitar em tempo calmo. Antes da construção, os topógrafos mapearam onde a água entrava nas ruas e onde os residentes mais velhos precisariam de ajuda para sair de casa. Os voluntários praticaram as novas rotas em tempo seco e descobriram que uma ponte era demasiado estreita para veículos de emergência. O plano foi ajustado antes da estação de tempestades seguinte. Empresas locais concordaram em guardar barreiras temporárias e as escolas acrescentaram instruções de inundação aos seus exercícios de segurança. As medições após cada tempestade foram comparadas com registos anteriores para que as dunas e a zona pantanosa pudessem ser reparadas onde a erosão era maior. Alguns moradores queriam inicialmente uma única defesa visível porque parecia mais simples. Oficinas públicas mostraram por que várias medidas ligadas ofereciam maior resiliência: se um elemento fosse danificado, os outros ainda poderiam reduzir os danos. A câmara publicou custos de manutenção e resultados de inspeção em vez de tratar a inauguração como o fim do projeto. Esta revisão contínua ajudou a vila a adaptar-se às mudanças do nível do mar e do clima. A abordagem não prometia segurança perfeita. Combinava proteção natural, infraestrutura fiável, avisos, prática de evacuação e responsabilidade partilhada para gerir abertamente o risco restante.',
      mainIdea: 'Medidas naturais e práticas combinadas reduziram o risco de inundação.',
      mainIdeaOptions: ['Medidas naturais e práticas combinadas reduziram o risco de inundação.', 'A vila parou todas as tempestades construindo um único muro.', 'O turismo foi a única razão para restaurar a costa.'],
      keyDetailQuestion: 'O que abrandou a maré de tempestade?',
      keyDetail: 'a zona pantanosa',
    },
  },
  hi: {
    speech_a: {
      passage: 'एक तटीय नगर में दशकों से हर सर्दी में बाढ़ आती थी। एक ही ऊंची दीवार बनाने के बजाय, निवासियों ने रेत के टीलों को फिर से बनाया, दलदली क्षेत्र को चौड़ा किया और सबसे निचले पैदल रास्तों को ऊंचा किया। परियोजना के बाद पहली आंधी में पानी फिर भी ऊंचा आया, लेकिन दलदल ने तूफानी लहर को धीमा किया और टीलों ने घरों को लहरों से बचाया। इंजीनियरों ने चेतावनी दी कि कोई एक उपाय हर जोखिम को समाप्त नहीं कर सकता। इसलिए नगर परिषद ने भू-दृश्य कार्य को स्पष्ट निकासी मार्गों और नियमित चेतावनी अभ्यासों के साथ जोड़ा। परियोजना इसलिए सफल हुई क्योंकि प्राकृतिक अवरोध, व्यावहारिक योजना और समुदाय की तैयारी ने एक-दूसरे का साथ दिया। इससे नया आवास भी बना और शांत मौसम में तट पर जाना आसान हुआ। निर्माण शुरू होने से पहले सर्वेक्षकों ने नक्शा बनाया कि पानी सड़कों में कहां प्रवेश करता है और किन बुजुर्ग निवासियों को घर छोड़ने में मदद चाहिए होगी। स्वयंसेवकों ने सूखे मौसम में नए मार्गों का अभ्यास किया और पाया कि एक पुल आपातकालीन वाहनों के लिए बहुत संकरा था। अगली तूफान ऋतु से पहले योजना बदली गई। स्थानीय व्यवसायों ने अस्थायी अवरोध रखने पर सहमति दी और स्कूलों ने अपनी सुरक्षा कवायदों में बाढ़ संबंधी निर्देश जोड़े। हर तूफान के बाद के मापों की तुलना पुराने आंकड़ों से की गई, ताकि जहां कटाव सबसे अधिक हो वहां टीलों और दलदल की मरम्मत की जा सके। कुछ निवासी शुरू में एक ही दिखाई देने वाली रक्षा चाहते थे क्योंकि वह सरल लगती थी। सार्वजनिक कार्यशालाओं ने दिखाया कि कई जुड़े हुए उपाय अधिक लचीलापन देते हैं: यदि एक तत्व क्षतिग्रस्त हो जाए, तो दूसरे फिर भी हानि कम कर सकते हैं। परिषद ने उद्घाटन को परियोजना का अंत मानने के बजाय रखरखाव लागत और निरीक्षण परिणाम प्रकाशित किए। इस निरंतर समीक्षा ने नगर को समुद्र-स्तर और मौसम में बदलाव के अनुकूल होने में मदद दी। यह तरीका पूर्ण सुरक्षा का वादा नहीं करता था। इसने प्राकृतिक सुरक्षा, भरोसेमंद आधारभूत संरचना, चेतावनियों, निकासी अभ्यास और साझा जिम्मेदारी को जोड़ा ताकि शेष जोखिम का खुलकर प्रबंधन हो सके।',
      mainIdea: 'प्राकृतिक और व्यावहारिक उपायों के संयोजन ने बाढ़ का जोखिम कम किया।',
      mainIdeaOptions: ['प्राकृतिक और व्यावहारिक उपायों के संयोजन ने बाढ़ का जोखिम कम किया।', 'नगर ने एक दीवार बनाकर सभी तूफान रोक दिए।', 'तट को बहाल करने का एकमात्र कारण पर्यटन था।'],
      keyDetailQuestion: 'तूफानी लहर को किसने धीमा किया?',
      keyDetail: 'दलदल',
    },
  },
  ar: {
    speech_a: {
      passage: 'كانت بلدة ساحلية تتعرض للفيضانات كل شتاء منذ عقود. وبدلاً من بناء جدار واحد أعلى، رمم السكان الكثبان الرملية ووسعوا منطقة مستنقعية ورفعوا أخفض الممرات. جلبت أول عاصفة بعد المشروع مياهاً مرتفعة أيضاً، لكن المستنقع أبطأ اندفاع العاصفة وحمت الكثبان المنازل من الأمواج. وحذر المهندسون من أن إجراءً واحداً لا يمكنه إزالة كل المخاطر. لذلك جمع المجلس المحلي بين أعمال تنسيق الأرض ومسارات إخلاء واضحة واختبارات إنذار منتظمة. نجح المشروع لأن الحواجز الطبيعية والتخطيط العملي واستعداد المجتمع دعم بعضها بعضاً. كما أنشأ موطناً جديداً للكائنات وجعل زيارة الشاطئ أسهل في الطقس الهادئ. قبل بدء البناء، رسم المساحون خريطة للأماكن التي تدخل منها المياه إلى الشوارع وللمواضع التي يحتاج فيها السكان الأكبر سناً إلى مساعدة لمغادرة منازلهم. تدرب المتطوعون على المسارات الجديدة في الطقس الجاف، وكشف ذلك أن أحد الجسور أضيق من أن تمر به مركبات الطوارئ. عُدلت الخطة قبل موسم العواصف التالي. ووافقت الشركات المحلية على تخزين حواجز مؤقتة، وأضافت المدارس تعليمات الفيضانات إلى تدريبات السلامة. وقورنت القياسات بعد كل عاصفة بالسجلات السابقة كي تُصلح الكثبان والمستنقع في الأماكن الأكثر تعرضاً للتآكل. أراد بعض السكان في البداية دفاعاً ظاهراً واحداً لأنه بدا أبسط. وأظهرت ورش العمل العامة سبب توفير عدة إجراءات مترابطة قدرة أكبر على الصمود: فإذا تضرر عنصر واحد، ظلت العناصر الأخرى قادرة على تقليل الضرر. نشر المجلس تكاليف الصيانة ونتائج الفحص بدلاً من اعتبار الافتتاح نهاية المشروع. ساعدت هذه المراجعة المستمرة البلدة على التكيف مع تغير مستوى البحر والطقس. لم يعد النهج بأمان كامل. بل جمع الحماية الطبيعية والبنية التحتية الموثوقة والإنذارات والتدرب على الإخلاء والمسؤولية المشتركة كي تُدار المخاطر المتبقية بصورة علنية.',
      mainIdea: 'قللت إجراءات طبيعية وعملية مترابطة من خطر الفيضانات.',
      mainIdeaOptions: ['قللت إجراءات طبيعية وعملية مترابطة من خطر الفيضانات.', 'أوقفت البلدة كل العواصف ببناء جدار واحد.', 'كان السياح السبب الوحيد لترميم الساحل.'],
      keyDetailQuestion: 'ما الذي أبطأ اندفاع العاصفة؟',
      keyDetail: 'المستنقع',
    },
  },
  ja: {
    speech_a: {
      passage: 'ある沿岸の町では、何十年もの間、毎年冬に洪水が起きていました。住民は一つの高い壁を造る代わりに、砂丘を復元し、湿地を広げ、最も低い歩道をかさ上げしました。事業後の最初の嵐でも水位は高くなりましたが、湿地が高潮の勢いを弱め、砂丘が家を波から守りました。技術者は、一つの対策だけで全ての危険をなくすことはできないと警告しました。そこで町議会は、景観の整備を明確な避難経路と定期的な警報訓練に組み合わせました。自然の障壁、実用的な計画、地域の備えが互いを支えたため、この事業は成功しました。また、新しい生息地が生まれ、穏やかな天候には海岸を訪れやすくなりました。工事前に測量士は、水がどこから道路に入るのか、また高齢の住民が家を離れる際にどこで助けを必要とするかを地図にしました。ボランティアは乾いた天候で新しい経路を練習し、その結果、一つの橋が緊急車両には狭すぎることが分かりました。計画は次の嵐の季節の前に調整されました。地元企業は仮設の障壁を保管することに同意し、学校は安全訓練に洪水時の指示を加えました。砂丘と湿地を浸食が最も大きい場所で修復できるよう、各嵐の後の測定値を以前の記録と比較しました。最初は、より簡単に見える一つの目に見える防御を望む住民もいました。公開ワークショップでは、複数のつながった対策の方が回復力をもたらす理由が示されました。一つの要素が損傷しても、他の要素が被害を減らせるからです。町議会は、開所式を事業の終わりとせず、維持費と点検結果を公表しました。この継続的な見直しは、海面や気象の変化に町が適応する助けとなりました。この方法は完全な安全を約束するものではありません。自然の保護、信頼できるインフラ、警報、避難訓練、責任の共有を組み合わせ、残る危険を公開して管理できるようにしたのです。',
      mainIdea: '自然対策と実用的な対策を組み合わせることで、洪水の危険を減らした。',
      mainIdeaOptions: ['自然対策と実用的な対策を組み合わせることで、洪水の危険を減らした。', '一つの壁を造ることで全ての嵐を止めた。', '海岸を復元した唯一の理由は観光だった。'],
      keyDetailQuestion: '何が高潮の勢いを弱めましたか？',
      keyDetail: '湿地',
    },
  },
});

export const SPEECH_IN_NOISE_SUPPORTED_LANGUAGES = Object.freeze([
  'en', ...Object.keys(SPEECH_IN_NOISE_LANGUAGE_OVERRIDES),
]);

export function localizedSpeechInNoiseForm(form, language = 'en') {
  const locale = String(language || 'en').split('-')[0].toLowerCase();
  const override = SPEECH_IN_NOISE_LANGUAGE_OVERRIDES[locale]?.[form.id];
  return {
    ...form,
    ...(override || {}),
    language: override ? locale : 'en',
    language_pack_status: override ? 'candidate_translation' : 'candidate_source_english',
  };
}
