name: personal-pc
version: "1.0"
models:
  - name: Qwen 7B
    provider: ollama
    model: qwen2.5-coder:7b
    apiBase: http://10.0.0.136:11434
    context_length: 32768
    roles:
      - chat
      - edit
      - apply
tab_autocomplete:
  name: Autocomplete
  provider: ollama
  model: qwen2.5-coder:7b
  apiBase: http://10.0.0.136:11434
